-- BVD_DebugMenu (v0.1.9): right-click context menu DROPPED.
--
-- Users reported the "Better Vehicle Dynamics > Open Vehicle Spawner"
-- right-click option was clutter — every right-click on the ground showed
-- it for admin / SP / -debug sessions. v0.1.9 removes the right-click
-- registration entirely; the spawner is now opened via console command:
--
--   /bvd-spawn       (typed into the SP/MP chat)
--
-- The spawner panel itself is unchanged — only the way it's launched.
-- This file is kept so existing world saves with references don't fail to
-- load; once a future release confirms no save migration concerns, it can
-- be deleted entirely.
